version: "3"
services:
  #app:
    #restart: always
    #build: ./app
    #links:
    #  - db
    #ports:
    #  - "5000:5000"

  db:
    image: mysql:8.0.21
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8087:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  mysql_vol:
    driver: local